[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
endcoin = "3ueQV5DMwmnif9JBmf7SSvD6Lsf13nBu4dzCQfsjZX3d"

[programs.devnet]
endcoin = "3ueQV5DMwmnif9JBmf7SSvD6Lsf13nBu4dzCQfsjZX3d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/andrew/.config/solana/wba-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
emit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/emit.ts"
deploy-0 = "yarn run ts-node deployment/00_generate_keypairs.ts"
deploy-1 = "yarn run ts-node deployment/create-amm.ts"
deploy-2 = "yarn run ts-node deployment/02_create-metadata.ts"
deploy-3 = "yarn run ts-node deployment/create-pool.ts"
swap = "yarn run ts-node deployment/swap.ts"



[test.validator]
url = "https://api.mainnet-beta.solana.com"
