[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
endcoin = "ENDgsTHhw9x8c3d49HQe5QuvzQPbL9BCHGs5fd9vgphp"

[programs.devnet]
endcoin = "ENDgsTHhw9x8c3d49HQe5QuvzQPbL9BCHGs5fd9vgphp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/andrew/.config/solana/wba-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
gettime = "yarn run ts-node tests/000_gettime.ts"
emit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/emit.ts"
test-0 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test.ts"
deploy-0 = "yarn run ts-node deployment/00_generate_keypairs.ts"
deploy-1 = "yarn run ts-node deployment/create-amm.ts"
deploy-2 = "yarn run ts-node deployment/02_create-metadata.ts"
deploy-3 = "yarn run ts-node deployment/create-pool.ts"
swap = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/swap.ts"



[test.validator]
url = "https://api.mainnet-beta.solana.com"
